#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 CHecking code formatting, testing and building your project before committing'

# Check Prettier standards
yarn run check-format ||
(
    echo '🤢🤮🤢🤮 Its RAW - Your code formatting looks disgusting. 🤢🤮🤢🤮
            Prettier Check Failed. Run yarn run format, add changes and try commit again.';
    false;
)

# Check ESLint Standards
yarn run check-lint ||
(
        echo '😤🏀👋😤 Get that weak spaghetti code out of here! 😤🏀👋😤 
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

# Check tsconfig standards
yarn run check-types ||
(
    echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
            Are you seriously trying to write that? Make the changes required above.'
    false;
)

# If everything passes... Now we can commit
echo '🤔🤔🤔🤔... Alright.... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
